### PR TITLE
made a file for Joe Andrieu's Characteristics of Sovereign Identity

### PR DESCRIPTION
**Pull request by infominer33**
The same as how the 10 principles have an individual file separate from Christopher Allen's post about them. The idea is to make it easier to compare the two. Just a small step towards organizing the continued thought on SSI, in hopes of stimulating dialog on the subject.

[edit] I also added a condensed version of Tim Ruff's 7 Myths of SSI.

### CODE REVIEW

**Review by ChristopherA — COMMENTED** [review]
Glad to see this started. @jandrieu have  there been any other thoughts since first introduced?

**Comment by infominer33** [comment]
>1 No disrespect to Christopher Allen’s opening to the conversation, The Path to Self Sovereign Identity [...] It gets a lot right, but leaves a few requirements out, e.g., recoverability and zero cost, and conflates “identities” and claims in an ambiguous manner. 

Dropping this here as useful to the discussion. I will continue with a more thorough examination to compare these *Characteristics of Sovereign Identity* with the "Ten Principles". 

I appreciate the attention to SDG 16.9 and that SSI should be of minimal cost to use, to be as widely useful as possible.

I'm not looking for immediate answers, but will continue considering the matter.

**Comment by infominer33** [comment]
Also, [A Gentle Introduction to Self Sovereign Identity](https://bitsonblocks.net/2017/05/17/gentle-introduction-self-sovereign-identity/) has a section "How would self-sovereign identity work for the user?" that I think would make a good addition to this collection, but maybe not in its current form.

I feel like here are the makings of a post about SSI, as an update and acknowledging how thought has developed since 2016. Which is something I'm working on anyways, so. I could maybe come up with a draft, but I don't know the best way to get it into others hands to improve upon it.

I'm a newb to SSI, so I see my work as mainly editorial, but I'm happy to gather the best thought I can find on the subject into a file for consideration.

**Comment by ChristopherA** [comment]
There is also [How to Convince Dad* of the Importance of Self-Sovereign Identity (* and your sister and your daughter and your best friend and your nephew)](https://github.com/WebOfTrustInfo/rwot7/blob/master/final-documents/convincing-dad.md).

**Comment by infominer33** [comment]
https://github.com/infominer33/self-sovereign-identity/blob/draft/evolution-of-ssi.md
is the beginnings of organized thought around the subject

**Comment by ChristopherA** [comment]
@infominer33 Are you ready for us to merge this? Let me know.

**Comment by infominer33** [comment]
yes, thank you @ChristopherA I've now migrated my work to a draft branch, I think this is plenty good for now. I'm going to keep digging for any other valuable SSI insights, and appreciate your mentioning "How to convince your dad."

Thanks again, Christopher!

**Comment by ChristopherA** [comment]
Thank you for contributing!

**Pull request merged**
